version: '3'
services:
  node:
    build: ./server
    command: npm start
    depends_on:
      - mongo
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo:4.1
    ports:
      - "27017:27017"
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443