version: '3'
services:
  node:
    build: ./server
    command: npm start
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
  mongo:
    container_name: mongo
    image: mongo:4.1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./client/build:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443